"""add_product_type_keyword_to_pricing_rules

Revision ID: 002fc6b7b67d
Revises: a54f797a7f31
Create Date: 2025-10-28 07:33:07.767748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002fc6b7b67d'
down_revision = 'a54f797a7f31'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pricing_rules', sa.Column('product_type_keyword', sa.String(length=200), nullable=True, comment='商品タイプキーワード（extracted_memoの値、例: ハードケース、手帳型カバー/mirror）'))
    op.alter_column('pricing_rules', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='商品ID（個別商品指定の場合）',
               existing_comment='商品ID')
    op.create_index(op.f('ix_pricing_rules_product_type_keyword'), 'pricing_rules', ['product_type_keyword'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pricing_rules_product_type_keyword'), table_name='pricing_rules')
    op.alter_column('pricing_rules', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment='商品ID',
               existing_comment='商品ID（個別商品指定の場合）')
    op.drop_column('pricing_rules', 'product_type_keyword')
    # ### end Alembic commands ###
