"""Add mapping_template table

Revision ID: 053764b8351d
Revises: 
Create Date: 2025-10-27 07:56:06.905207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '053764b8351d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mapping_templates',
    sa.Column('template_name', sa.String(length=100), nullable=False, comment='テンプレート名'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='説明'),
    sa.Column('file_pattern', sa.String(length=200), nullable=True, comment='ファイル名パターン（例: order_*.csv）'),
    sa.Column('file_type', sa.String(length=50), nullable=True, comment='ファイルタイプ: csv, excel, pdf, txt'),
    sa.Column('column_mapping', sa.JSON(), nullable=False, comment='列マッピング設定（JSON）'),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='デフォルトテンプレートフラグ'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='有効フラグ'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_name')
    )
    op.create_index(op.f('ix_mapping_templates_id'), 'mapping_templates', ['id'], unique=False)
    op.create_foreign_key(None, 'invoices', 'customer_companies', ['customer_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'customer_companies', ['customer_id'], ['id'])
    op.create_foreign_key(None, 'pricing_rules', 'customer_companies', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pricing_rules', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_index(op.f('ix_mapping_templates_id'), table_name='mapping_templates')
    op.drop_table('mapping_templates')
    # ### end Alembic commands ###
