"""add_device_and_size_learning_tables

Revision ID: 1a27d5949d58
Revises: 38865d2f0fcb
Create Date: 2025-11-10 08:28:10.979522

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1a27d5949d58'
down_revision = '38865d2f0fcb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pattern', sa.String(length=255), nullable=False),
    sa.Column('device_name', sa.String(length=100), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_patterns_brand'), 'device_patterns', ['brand'], unique=False)
    op.create_index(op.f('ix_device_patterns_confidence'), 'device_patterns', ['confidence'], unique=False)
    op.create_index(op.f('ix_device_patterns_device_name'), 'device_patterns', ['device_name'], unique=False)
    op.create_index(op.f('ix_device_patterns_id'), 'device_patterns', ['id'], unique=False)
    op.create_index(op.f('ix_device_patterns_pattern'), 'device_patterns', ['pattern'], unique=False)
    op.create_table('size_patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pattern', sa.String(length=255), nullable=False),
    sa.Column('size', sa.String(length=20), nullable=False),
    sa.Column('device_name', sa.String(length=100), nullable=True),
    sa.Column('brand', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_size_patterns_brand'), 'size_patterns', ['brand'], unique=False)
    op.create_index(op.f('ix_size_patterns_confidence'), 'size_patterns', ['confidence'], unique=False)
    op.create_index(op.f('ix_size_patterns_device_name'), 'size_patterns', ['device_name'], unique=False)
    op.create_index(op.f('ix_size_patterns_id'), 'size_patterns', ['id'], unique=False)
    op.create_index(op.f('ix_size_patterns_pattern'), 'size_patterns', ['pattern'], unique=False)
    op.create_index(op.f('ix_size_patterns_size'), 'size_patterns', ['size'], unique=False)
    op.drop_index('idx_device_brand', table_name='device_attributes')
    op.drop_index('idx_device_brand_name', table_name='device_attributes')
    op.drop_index('idx_device_name', table_name='device_attributes')
    op.drop_table('device_attributes')
    op.drop_index('idx_designs_case_type', table_name='designs')
    op.drop_index('idx_designs_design_no', table_name='designs')
    op.drop_index('idx_designs_status', table_name='designs')
    op.drop_table('designs')
    op.alter_column('product_type_patterns', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('product_type_patterns', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_product_type_patterns_confidence', table_name='product_type_patterns')
    op.drop_index('idx_product_type_patterns_pattern', table_name='product_type_patterns')
    op.drop_index('idx_product_type_patterns_product_type', table_name='product_type_patterns')
    op.create_index(op.f('ix_product_type_patterns_confidence'), 'product_type_patterns', ['confidence'], unique=False)
    op.create_index(op.f('ix_product_type_patterns_id'), 'product_type_patterns', ['id'], unique=False)
    op.create_index(op.f('ix_product_type_patterns_pattern'), 'product_type_patterns', ['pattern'], unique=False)
    op.create_index(op.f('ix_product_type_patterns_product_type'), 'product_type_patterns', ['product_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_type_patterns_product_type'), table_name='product_type_patterns')
    op.drop_index(op.f('ix_product_type_patterns_pattern'), table_name='product_type_patterns')
    op.drop_index(op.f('ix_product_type_patterns_id'), table_name='product_type_patterns')
    op.drop_index(op.f('ix_product_type_patterns_confidence'), table_name='product_type_patterns')
    op.create_index('idx_product_type_patterns_product_type', 'product_type_patterns', ['product_type'], unique=False)
    op.create_index('idx_product_type_patterns_pattern', 'product_type_patterns', ['pattern'], unique=False)
    op.create_index('idx_product_type_patterns_confidence', 'product_type_patterns', ['confidence'], unique=False)
    op.alter_column('product_type_patterns', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('product_type_patterns', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_table('designs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('design_no', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='デザイン番号（SKU）'),
    sa.Column('design_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='デザイン名'),
    sa.Column('case_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='商品タイプ（手帳型、ハードケース等）'),
    sa.Column('material', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='素材'),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'有効'::character varying"), autoincrement=False, nullable=True, comment='ステータス（有効/無効）'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True, comment='作成日時'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True, comment='更新日時'),
    sa.PrimaryKeyConstraint('id', name='designs_pkey')
    )
    op.create_index('idx_designs_status', 'designs', ['status'], unique=False)
    op.create_index('idx_designs_design_no', 'designs', ['design_no'], unique=True)
    op.create_index('idx_designs_case_type', 'designs', ['case_type'], unique=False)
    op.create_table('device_attributes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('brand', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='ブランド名（iPhone, Galaxy, AQUOS等）'),
    sa.Column('device_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='機種名（iPhone 15 Pro, Galaxy A54等）'),
    sa.Column('size_category', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='サイズカテゴリ（L, i6, 特大等）'),
    sa.Column('attribute_value', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='その他属性値'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='device_attributes_pkey'),
    sa.UniqueConstraint('brand', 'device_name', name='uq_device_attributes_brand_device_name')
    )
    op.create_index('idx_device_name', 'device_attributes', ['device_name'], unique=False)
    op.create_index('idx_device_brand_name', 'device_attributes', ['brand', 'device_name'], unique=False)
    op.create_index('idx_device_brand', 'device_attributes', ['brand'], unique=False)
    op.drop_index(op.f('ix_size_patterns_size'), table_name='size_patterns')
    op.drop_index(op.f('ix_size_patterns_pattern'), table_name='size_patterns')
    op.drop_index(op.f('ix_size_patterns_id'), table_name='size_patterns')
    op.drop_index(op.f('ix_size_patterns_device_name'), table_name='size_patterns')
    op.drop_index(op.f('ix_size_patterns_confidence'), table_name='size_patterns')
    op.drop_index(op.f('ix_size_patterns_brand'), table_name='size_patterns')
    op.drop_table('size_patterns')
    op.drop_index(op.f('ix_device_patterns_pattern'), table_name='device_patterns')
    op.drop_index(op.f('ix_device_patterns_id'), table_name='device_patterns')
    op.drop_index(op.f('ix_device_patterns_device_name'), table_name='device_patterns')
    op.drop_index(op.f('ix_device_patterns_confidence'), table_name='device_patterns')
    op.drop_index(op.f('ix_device_patterns_brand'), table_name='device_patterns')
    op.drop_table('device_patterns')
    # ### end Alembic commands ###
