"""Add product classification fields to OrderItem

Revision ID: 1a78f5997177
Revises: device_model_20251029
Create Date: 2025-10-29 15:25:46.623687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a78f5997177'
down_revision = 'device_model_20251029'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('product_type', sa.String(length=100), nullable=True, comment='商品タイプ（ハードケース/手帳型カバーなど）'))
    op.add_column('order_items', sa.Column('device_info', sa.String(length=100), nullable=True, comment='機種情報（iPhone 15 Pro/AQUOS wish4など）'))
    op.add_column('order_items', sa.Column('size_info', sa.String(length=50), nullable=True, comment='サイズ情報（L/i6/特大など）'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'size_info')
    op.drop_column('order_items', 'device_info')
    op.drop_column('order_items', 'product_type')
    # ### end Alembic commands ###
