"""add_closing_payment_day_to_customer

Revision ID: 1cc2f3592c37
Revises: 053764b8351d
Create Date: 2025-10-28 06:16:45.472692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cc2f3592c37'
down_revision = '053764b8351d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_companies', sa.Column('closing_day', sa.Integer(), nullable=True, comment='締め日（1-31、0=月末）'))
    op.add_column('customer_companies', sa.Column('payment_day', sa.Integer(), nullable=True, comment='支払い日（1-31、0=月末）'))
    op.add_column('customer_companies', sa.Column('payment_month_offset', sa.Integer(), nullable=True, comment='支払い月のオフセット（0=当月、1=翌月、2=翌々月）'))
    op.alter_column('customer_companies', 'payment_terms',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=200),
               comment='支払条件（説明文）',
               existing_comment='支払期限（日数）',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer_companies', 'payment_terms',
               existing_type=sa.String(length=200),
               type_=sa.INTEGER(),
               comment='支払期限（日数）',
               existing_comment='支払条件（説明文）',
               existing_nullable=True)
    op.drop_column('customer_companies', 'payment_month_offset')
    op.drop_column('customer_companies', 'payment_day')
    op.drop_column('customer_companies', 'closing_day')
    # ### end Alembic commands ###
