"""add_customer_id_to_mapping_templates

Revision ID: a54f797a7f31
Revises: 1cc2f3592c37
Create Date: 2025-10-28 06:47:57.408573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a54f797a7f31'
down_revision = '1cc2f3592c37'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mapping_templates', sa.Column('customer_id', sa.Integer(), nullable=True, comment='顧客ID（NULLの場合は汎用テンプレート）'))
    op.drop_constraint('mapping_templates_template_name_key', 'mapping_templates', type_='unique')
    op.create_index(op.f('ix_mapping_templates_customer_id'), 'mapping_templates', ['customer_id'], unique=False)
    op.create_foreign_key(None, 'mapping_templates', 'customer_companies', ['customer_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mapping_templates', type_='foreignkey')
    op.drop_index(op.f('ix_mapping_templates_customer_id'), table_name='mapping_templates')
    op.create_unique_constraint('mapping_templates_template_name_key', 'mapping_templates', ['template_name'])
    op.drop_column('mapping_templates', 'customer_id')
    # ### end Alembic commands ###
