"""add product classification fields to order_items

Revision ID: acf3d78dbde3
Revises: e5539ca4aa58
Create Date: 2025-10-30 07:53:04.892998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acf3d78dbde3'
down_revision = 'e5539ca4aa58'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('product_type', sa.String(length=100), nullable=True, comment='商品タイプ（ハードケース/手帳型カバーなど）'))
    op.add_column('order_items', sa.Column('device_info', sa.String(length=100), nullable=True, comment='機種情報（iPhone 15 Pro/AQUOS wish4など）'))
    op.add_column('order_items', sa.Column('size_info', sa.String(length=50), nullable=True, comment='サイズ情報（L/i6/特大など）'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'size_info')
    op.drop_column('order_items', 'device_info')
    op.drop_column('order_items', 'product_type')
    # ### end Alembic commands ###
