"""add customer_identifiers table

Revision ID: e5539ca4aa58
Revises: 002fc6b7b67d
Create Date: 2025-10-28 07:57:39.362992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5539ca4aa58'
down_revision = '002fc6b7b67d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_identifiers',
    sa.Column('customer_id', sa.Integer(), nullable=False, comment='取引先ID'),
    sa.Column('identifier_type', sa.String(length=50), nullable=False, comment='識別情報タイプ（csv_name, phone, address, email, etc.）'),
    sa.Column('identifier_value', sa.String(length=500), nullable=False, comment='識別情報の値'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier_type', 'identifier_value', name='uq_identifier_type_value')
    )
    op.create_index(op.f('ix_customer_identifiers_customer_id'), 'customer_identifiers', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_identifiers_id'), 'customer_identifiers', ['id'], unique=False)
    op.create_index(op.f('ix_customer_identifiers_identifier_type'), 'customer_identifiers', ['identifier_type'], unique=False)
    op.create_index(op.f('ix_customer_identifiers_identifier_value'), 'customer_identifiers', ['identifier_value'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_identifiers_identifier_value'), table_name='customer_identifiers')
    op.drop_index(op.f('ix_customer_identifiers_identifier_type'), table_name='customer_identifiers')
    op.drop_index(op.f('ix_customer_identifiers_id'), table_name='customer_identifiers')
    op.drop_index(op.f('ix_customer_identifiers_customer_id'), table_name='customer_identifiers')
    op.drop_table('customer_identifiers')
    # ### end Alembic commands ###
